info:
  description: "Merchant exceptions"
  version: '1.0'
  title: Merchant exceptions

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.MER.Exceptions
  apiName: TBD
  namespace: IMN.MER.Exceptions
  comment: |
    IMN.MER.Exceptions
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.MER.Schemas
  references:
  - IMN.Schemas
  - IMN.MER.Schemas
  

definitions:
  merchantCodeAlreadyUsedException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - merchantCode
    description: |
      The merchant code '{merchantCode}' already exists
    properties:
      merchantCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
        
        
  invalidMarketplaceCredentialException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - marketplaceApiCredential
    description: |
      Marketplace credentials are not recognized, please check them and try again
    properties:
      marketplaceApiCredential: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceApiCredential'
        
  subscriptionNotAcceptedException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - marketplaceCode
    description: |
      The subscription has not yet been accepted by the marketplace '{marketplaceCode}'
    properties:
      marketplaceCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
    
  notOfferSourceMarketplaceException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - marketplaceCode
    description: |
      The marketplace '{marketplaceCode}' is not the offer source
    properties:
      marketplaceCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
        
  credentialNotConfiguredException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - marketplaceCode
    description: |
      The credential are not configured for the marketplace '{marketplaceCode}'
    properties:
      marketplaceCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
        
  partnerHttpException:
    x-exclude: true
    x-format: Exception
    x-transient: false
    x-technical: true
    type: object
    required: 
    - correlationId
    - marketplaceCode
    - merchantCode
    - logUri
    - httpStatus
    - operationName
    description: |
      The partner http request is in error
    properties:
      correlationId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/correlationId'
      marketplaceCode: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
      merchantCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      logUri:
        type: string
        format: uri
      httpStatus:
        type: string
        format: httpStatusCode
      operationName:
        type: string
        
  partnerInvalidResponse:
    x-exclude: true
    x-format: Exception
    x-transient: false
    x-technical: true
    type: object
    required: 
    - correlationId
    - marketplaceCode
    - merchantCode
    - exceptionMessage
    - operationName
    description: |
      The partner http response is invalid
    properties:
      correlationId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/correlationId'
      marketplaceCode: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
      merchantCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      exceptionMessage:
        type: string
      operationName:
        type: string
        
        
  invalidOperationOnDeclaredMerchantOffersSourceMarketplaceException:
    x-format: Exception
    x-transient: false
    x-technical: false
    type: object
    required: 
    - merchantCode
    - sourceMarketplaceCode
    - operationName
    description: |
      The operation '{operationName}' is invalid on a offers source marketplace.
    properties:
      merchantCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      sourceMarketplaceCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
      operationName:
        type: string
        
  dependencyProjectionException:
    x-format: Exception
    x-transient: false
    x-technical: true
    type: object
    required: 
    - merchantCode
    - projectionType
    - projectionMessageId
    - currentMessageId
    description: |
      Projection '{projectionType}' ('{projectionMessageId}') failed for merchantCode '{merchantCode}'. Current messageId is '{currentMessageId}'
    properties:
      merchantCode: 
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      projectionType:
        type: string
      projectionMessageId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/messageId'
      currentMessageId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/messageId'
        
#  emailBadFormattedException:
#    x-format: Exception
 #   x-transient: true
  #  x-technical: false
   # type: object
  #  description: | 
  #    Format of the email is not valid
  #  properties:
  #    walletPropertyCode: 
  #      $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
  
#  sortException:
#    x-format: Exception
#    x-transient: false
#    x-technical: true
#    type: object
#    description: |
#      example
#    properties:
#      sort:
#        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/sort'
    
  
      

# responses:
  # GeneralError:
  #   description: General Error
  #   schema:
  #     $ref: '#/definitions/ErrorModel'

# parameters:
  # skipParam:
  #   name: "skip"
  #   in: "query"
  #   description: "number of items to skip"
  #   type: "integer"

# pathitems:
  # EntityOperations:
  #   get:
  #     description: "Returns a pet based on ID"
  #     summary: "Find pet by ID"
  #     responses:
  #       default:
  #         $ref: '#/responses/GeneralError'