### Domains, a place to put your reusable components

### Examples...

info:
  description: IMN Core - Offer Messages
  version: '1.0'
  title: IMN - Offer Messages

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.Offer.Messages
  apiName: TBD
  namespace: IMN.Offer.Messages
  comment: |
    IMN.Offer.Messages
    changed to yaml format
  using:
  - IMN.Offer.Schemas

definitions:




    
  batchMerchantMarketplaceOfferChanges:
    x-format: Message
    type: object
    description: Contains all changes for one marketplace for one merchant
    properties:
      created:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantMarketplaceOffer'
      updated:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantMarketplaceOffer'
      deleted:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'    

    
  batchMerchantOfferChanges:
    x-format: Message
    type: object
    description: Contains all changes
    properties:
      created:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOffer'
      updated:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOffer'
      deleted:
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'