### Domains, a place to put your reusable components

### Examples...

info:
  description: IMN Core - Offer Messages
  version: '1.0'
  title: IMN - Offer Messages

x-beezup-ops:
  codeGenType: domain
  product: IMN-CORE
  repo: IMN
  appRoot: IMN.Offer.Messages
  apiName: TBD
  namespace: IMN.Offer.Messages
  comment: |
    IMN.Offer.Messages
    changed to yaml format
  using:
  - IMN.Offer.Schemas
  - IMN.Schemas
  references:
  - IMN.Offer.Schemas

definitions:

    

  batchMerchantOfferChanges:
    x-format: Message
    type: object
    description: Contains all changes for a merchant
    properties:
      offers:
        type: array
        minItems: 1
        maxItems: 1000
        description: Offers that need to be created or replaced
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOffer'
      deleted:
        type: array
        minItems: 1
        maxItems: 1000
        description: Deleted offers
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'
      unpublished:
        type: array
        minItems: 1
        maxItems: 1000
        description: Unpublished offers
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'