info:
  version: "1.0"
  title: IMN - ADAPTER - Order Schemas
  description: IMN - ADAPTER - Order Schemas

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.ADPT.Order.Schemas
  apiName: TBD
  namespace: IMN.ADPT.Order.Schemas
  comment: |
    IMN.ADPT.Order.Schemas
    Changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Order.Schemas
  - IMN.ADPT.Schemas
  references:
  - IMN.Order.Schemas
  - IMN.ADPT.Schemas

definitions:

  beezUPOrderId:
    description: The BeezUP Order identifier
    type: string
    format: uuid
    example: '00000000000000000000000000000000000000000000000'

  beezUPOrderIdentifier:
    description: The BeezUP order identifier
    type: object
    required:
    - marketplaceTechnicalCode
    - accountId
    - beezUPOrderUUID
    properties:
      marketplaceTechnicalCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/adapter-schemas/1.0#/definitions/beezUPMarketplaceTechnicalCode'
      accountId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/adapter-schemas/1.0#/definitions/beezUPMarketplaceAccountId'
      beezUPOrderUUID:
        $ref: '#/definitions/beezUPOrderId'

  beezUPOrderChangeExecutionSummary:
    allOf:
    - type: object
      description: The BeezUP order change execution summary
      required:
      - executionUUID
      - correlationId
      - processingStatus
      properties:
        executionUUID:
          type: string
        correlationId:
          type: string
        marketplaceTechnicalCode:
          type: string
        accountId:
          type: integer
        beezUPOrderUUID:
          type: string
        processingStatus:
          type: string
        errorCode:
          type: string
        errorMessage:
          type: string
    - $ref: '#/definitions/beezUPOrderIdentifier'