info:
  version: "1.0"
  title: IMN - ADAPTER - Order Schemas
  description: IMN - ADAPTER - Order Schemas

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.ADPT.Order.Schemas
  apiName: TBD
  namespace: IMN.ADPT.Order.Schemas
  comment: |
    IMN.ADPT.Order.Schemas
    Changed to yaml format
  using:
  - BeezUP2.Framework.Messaging
  - IMN.Schemas
  - IMN.Order.Schemas
  - IMN.ADPT.Schemas
  references:
  - IMN.Order.Schemas
  - IMN.ADPT.Schemas

definitions:

  beezUPOrderId:
    description: The BeezUP Order identifier
    type: string
    format: uuid
    example: '00000000000000000000000000000000000000000000000'

  beezUPOrderIdentifier:
    description: The BeezUP order identifier
    type: object
    required:
    - marketplaceTechnicalCode
    - accountId
    - beezUPOrderId
    properties:
      marketplaceTechnicalCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/adapter-schemas/1.0#/definitions/beezUPMarketplaceTechnicalCode'
      accountId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/adapter-schemas/1.0#/definitions/beezUPMarketplaceAccountId'
      beezUPOrderId:
        $ref: '#/definitions/beezUPOrderId'

  beezUPOrderChangeExecutionSummary:
    allOf:
    - $ref: '#/definitions/beezUPOrderIdentifier'
    - type: object
      description: The BeezUP order change execution summary
      required:
      - executionId
      - correlationId
      - merchantCode
      - marketplaceCode
      - processingStatus
      properties:
        executionId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/adapter-schemas/1.0#/definitions/beezUPExecutionId'
        correlationId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/correlationId'
        merchantCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
        marketplaceCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
        processingStatus:
          type: string
        errorCode:
          type: string
        errorMessage:
          type: string