### Domains, a place to put your reusable components

### Examples...

info:
  version: '1.0'
  title: IMN - Merchant Events
  description: IMN - Merchant Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: TBD
  apiName: TBD
  namespace: IMN.MER.Events
  comment: |
    Add sourceMarketplaceCode in the externalMerchantMarketplaceSubscriptionsRequested
    IMN.MER.Events
  using:
  - IMN.MER.Schemas
  - IMN.Schemas
  - BeezUP2.Framework.Messaging
  - BeezUP2.ApiModels.Generated.Models.Generated

definitions:




  merchantEventPushed:
    x-exclude: true
    type: object
    discriminator: eventType
    required:
    - merchantCode
    - eventType
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      eventType:
        x-exclude: true
        type: string
    

  merchantCreated:
    x-format: Event
    type: object
    description: When the merchant creates his account on IMN 
    required:
    - merchantCode
    - userId
    - email
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      email:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
        
  merchantAcountInfoUpdated:
    x-format: Event
    description: When the merchant updates his account information
    type: object
    required: 
    - merchantCode
    - userId
    - companyName
    - lastName
    - firstName
    - country
    - phoneNumber
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      companyName:
        $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantCompanyName'
      lastName:
        type: string
      firstName:
        type: string
      country:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/countryIsoCodeAlpha3'
      phoneNumber:
        type: string
      imageUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
   
  
  
  
  merchantMarketplaceEventBase:
    x-exclude: true
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - type: object
      required:
      - marketplaceCode
      properties:
        marketplaceCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'

   
  merchantMarketplaceCredentialConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - credential
      properties:
        credential:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceApiCredential'
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
  
  
  merchantMarketplaceSubscriptionRequested:
    x-format: Event
    description: When the merchant marketplace subscription has been requested
    allOf: 
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        externalId:
          type: string
          description: If the request is coming from an external system we will keep the identifier

  merchantMarketplaceSubscriptionAccepted:
    x-format: Event
    description: When the marketplace accept the mechant subscription request
    allOf: 
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'


  merchantMarketplaceSubscriptionRefused:
    x-format: Event
    description: When the marketplace refuses the merchant subscription
    allOf: 
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - reason
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        reason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantMarketplaceSubscriptionRefusalReason'
  
  merchantMarketplaceSubscriptionBlocked:
    x-format: Event
    description: When the marketplace blocks the merchant subscription
    allOf: 
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - reason
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        reason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantMarketplaceSubscriptionRefusalReason'

  merchantOffersSourceMarketplaceDeclared:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
  
  merchantOffersSourceMarketplaceUndeclared:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
 
  merchantMarketplaceOfferImportationEnabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  merchantMarketplaceOfferImportationDisabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'


  merchantMarketplaceOfferPublicationEnabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  merchantMarketplaceOfferPublicationDisabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'



  merchantMarketplaceOrderImportationEnabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  merchantMarketplaceOrderImportationDisabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  externalMerchantMarketplaceSubscriptionsRequested:
    x-format: Event
    type: object
    description: When the merchant marketplace subscription has been requested
    required:
    - merchantCode
    - userId
    - targetMarketplacesSubscriptionRequested
    - subscriptionRequestUtcDate
    - salesforceSubscriptionId
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'

      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
          
      targetMarketplacesSubscriptionRequested:
        type: array
        minItems: 1
        uniqueItems: true
        items:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
      subscriptionRequestUtcDate:
        type: string
        format: date-time
        description: The exact date time of the subscription request
      salesforceSubscriptionId:
        type: string
        description: The Salesforce identifier of the subscription
        example: 'BLA0O00001v8aNuQAI'
        
  merchantMarketplacePricingSettingConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - ruleType
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        ruleType: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplacePricingRuleType'
        value:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplacePricingValue'
          
  merchantMarketplaceShippingPreprationSettingConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - preparationRuleType
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        preparationRuleType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplacePreparationRuleType'
        preparationDelay:
          type: number
          format: int32
          description: The delay considering the rule          
          
          
  merchantMarketplaceShippingDeliverySettingConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - deliveryMode
      - ruleType
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        deliveryMode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/deliveryMode'
        ruleType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplaceShippingChargeRuleType'
        charge:
          type: number
          example: 3.35
          description: The charge for this delivery mode considering the rule
        additionalCharge:
          type: number
          example: 1.52
          description: The additional charge for this delivery mode         
          
  merchantMarketplaceShippingDeliverySettingDisabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  merchantMarketplaceShippingDeliverySettingDeleted:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

  merchantMarketplaceShippingDeliverySettingEnabled:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
  
  marketplaceMerchantCodeConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceEventBase'
    - type: object
      required:
      - merchantCode
      - userId
      - marketplaceCode
      - marketplaceMerchantCode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        marketplaceMerchantCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceMerchantCode'
          
  merchantCurrencyConversionConfigured:
    x-format: Event
    allOf:
    - $ref: '#/definitions/merchantEventPushed'
    - type: object
      required:
      - userId
      - from
      - to
      - rate
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        from:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/currencyCode'
        to:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/currencyCode'
        rate:
          type: number
          format: decimal
          description: The rate conversion to be applied from the currency to another one