### Domains, a place to put your reusable components

### Examples...

info:
  description: IMN Core - Offer Schemas
  version: '1.0'
  title: IMN - Offer Schemas

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.Offer.Schemas
  apiName: TBD
  namespace: IMN.Offer.Schemas
  comment: |
    20180509 - test
    IMN.Offer.Schemas
    changed to yaml format
  using:
  - IMN.Schemas

definitions:

  price:
    x-exclude: true
    type: number
    format: decimal
    description: The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes. http://schema.org/price

  priceCurrency:
    type: string
    description: |
      The offer price of a product, or of a price component when attached to PriceSpecification and its subtypes.
      Usage guidelines:
      Use the priceCurrency property (with ISO 4217 codes e.g. USD) instead of including ambiguous symbols such as $ in the value. http://schema.org/priceCurrency

  validFrom:
    type: string
    format: date-time
    description: The date when the item becomes valid. http://schema.org/validFrom

  validThrough:
    type: string
    format: date-time
    description: The date after when the item is not valid. For example the end of an offer, salary period, or a period of opening hours. http://schema.org/validThrough

  priceSpecification:
    type: object
    properties:
      price:
        $ref: '#/definitions/price'
      validFrom:
        $ref: '#/definitions/validFrom'
      validThrough:
        $ref: '#/definitions/validThrough'

  minPrice:
    type: number
    format: decimal
    description: The lowest price if the price is a range. http://schema.org/minPrice

  deliveryLeadTime:
    type: number
    format: int16
    description: The typical delay between the receipt of the order and the goods either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup. http://schema.org/deliveryLeadTime

  inventoryLevel:
    type: number
    format: decimal
    description: The current approximate inventory level for the item or items. http://schema.org/inventoryLevel

  fulfilledBy:
    type: string
    description: The marketplace in charge of the delivery on this offer.

  itemCondition:
    type: string
    enum:
    - NewCondition
    - RefurbishedCondition
    - UsedAsNewCondition
    - UsedVeryGoodCondition
    - UsedGoodCondition
    - UsedAcceptableCondition

  merchantOfferIdentifier:
    type: object
    required:
    - merchantCode
    - sku
    - gtin
    - itemCondition
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      sku:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/sku'
      gtin:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/gtin'
      itemCondition:
        $ref: '#/definitions/itemCondition'
      fulfilledBy:
        $ref: '#/definitions/fulfilledBy'

  merchantOfferList:
   allOf:
    - type: object
      properties:
        merchantOffers:
          type: array
          items:
           $ref: '#/definitions/merchantOffer'

  merchantOffer:
    allOf:
    - $ref: '#/definitions/merchantOfferIdentifier'
    - type: object
      description: The defaultDeliveryMethod is required if the deliverySpecifications is fulfilled
      required:
      - merchantCode
      - sku
      - gtin
      - itemCondition
      - price
      - priceCurrency
      - deliveryLeadTime
      - inventoryLevel
      - lastUpdateUtcDate
      properties:
        price:
          $ref: '#/definitions/price'
        priceCurrency:
          $ref: '#/definitions/priceCurrency'
        minPrice:
          $ref: '#/definitions/minPrice'
        discount:
          $ref: '#/definitions/priceSpecification'
        deliveryLeadTime:
          $ref: '#/definitions/deliveryLeadTime'
        inventoryLevel:
          $ref: '#/definitions/inventoryLevel'
        defaultDeliveryMethod:
          $ref: '#/definitions/deliveryMethod'
        deliverySpecifications:
          type: array
          items:
           $ref: '#/definitions/deliverySpecification'
        lastUpdateUtcDate:
          type: string
          format: date-time
          example: '2018-02-24T14:24:35'
        sourceMarketplaceCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'


  transportTime:
    type: number
    format: int16
    description: |
      To compute the shipping time, we sometimes ask for the typical delay from the moment the goods are either leaving the warehouse or being prepared for pickup, in case the delivery method is on site pickup. http://schema.org/deliveryLeadTime

  deliverySpecification:
    type: object
    required:
    - deliveryMethod
    - price
    properties:
      deliveryMethod:
        $ref: deliveryMethod
      price:
        $ref: '#/definitions/price'
      additionalPrice:
        $ref: '#/definitions/price'

      

  merchantOfferNoneImportationReasonCode:
    type: string
    description: A reason code related
    enum:
    - InvalidEAN
    - InvariantNotAppliable

  merchantOfferNoneImportationReason:
    type: object
    properties:
      code:
        $ref: '#/definitions/merchantOfferNoneImportationReasonCode'
      error:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userErrorMessage'
      propertyName:
        type: string
        description: The related property name causing the none importation of the offer
      actualValue:
        type: string
        description: The actual value causing the none importation of the offer