info:
  version: "1.0"
  title: IMN - Offer Exportation Commands

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  product: IMN-CORE
  appRoot: IMN.Offer.EXP.Commands
  apiName: TBD
  namespace: IMN.Offer.EXP.Commands
  comment: |
    IMN.Offer.EXP.Commands
    changed to yaml format
  using:
  - IMN.Schemas

definitions:
  
  initializeOffersExport:
    x-format: Command
    allOf:
      - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
      - type: object
        required: 
        - merchantCode
        - marketplaceCode
        properties:
          parentOperationName:
            type: string
        
  cancelInitOffersExport:
    x-format: Command
    allOf:
      - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
      - type: object
        required: 
        - merchantCode
        - marketplaceCode
        
  unpublishOffersExport:
    x-format: Command
    allOf:
      - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
      - type: object
        required: 
        - merchantCode
        - marketplaceCode

  cancelUnpublishOffersExport:
    x-format: Command
    allOf:
      - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
      - type: object
        required: 
        - merchantCode
        - marketplaceCode