### Domains, a place to put your reusable components

### Examples...
info:
  version: '1.0'
  title: IMN - Merchant Schemas
  description: IMN - Merchant Schemas

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.MER.Schemas
  apiName: TBD
  namespace: IMN.MER.Schemas
  comment: |
    IMN.MER.Schemas
    changed to yaml format
  using:
  - IMN.Schemas

definitions: 

  marketplaceSubscriptionStatus:
    description: The subscription status
    type: string
    enum:
    - notRequested
    - requested
    - accepted
    - declined
    - blocked
    example: accepted

  merchantMarketplaceSubscriptionRefusalReason:
    type: string
    minLength: 5
    x-minLength: 5
    maxLength: 4000
    x-maxLength: 4000
    description: The marketplace reason for the subscription's refusal
  
  merchantCompanyName:
    type: string
    minLength: 2
    x-minLength: 2
    maxLength: 100
    x-maxLength: 100
    description: Merchant's company name
    
  marketplaceCredentialStatus:
    description: The marketplace credential status
    type: string
    enum:
    - notConfigured
    - configured
    - expired
    example: configured



  marketplaceShippingSettingsStatus:
    description: The marketplace shipping settings status
    type: string
    enum:
    - notConfigured
    - configured

  marketplacePreparationRuleType:
    type: string
    enum:
    - Increase
    - Decrease
    - Same
    - Fixed
    default: Same
    example: Same


  marketplacePreparationSetting:
    type: object
    required: 
    - ruleType
    properties:
      ruleType:
        $ref: '#/definitions/marketplacePreparationRuleType'
      delay:
        type: integer
        format: int32
        description: The delay considering the rule
  
  marketplaceShippingSettings:
    type: object
    required:
    - preparationSetting
    - deliverySettings
    properties:
      preparationSetting:
        $ref: '#/definitions/marketplacePreparationSetting'
          
      deliverySettings:
        $ref: '#/definitions/marketplaceDeliverySettingList'
          
  deliveryMode:
    type: string
    example: Standard
    x-lov: DeliveryMode
    
  marketplaceDeliverySettingList:
    type: array
    items:
      $ref: '#/definitions/marketplaceDeliverySetting'
  
  marketplaceDeliverySetting:
    type: object
    required:
    - deliveryMode
    - ruleType
    properties:
      deliveryMode:
        $ref: '#/definitions/deliveryMode'
      ruleType:
        $ref: '#/definitions/marketplaceShippingChargeRuleType'
      charge:
        type: number
        example: 3.35
        description: The charge for this delivery mode considering the rule
      additionalCharge:
        type: number
        example: 1.52
        description: The additional charge for this delivery mode

 
  
  marketplacePricingValue:
    type: number
    pattern: ^([0-9]{1,13}[.]*[0-9]{0,6})$
    x-pattern: ^([0-9]{1,13}[.]*[0-9]{0,6})$
    example: 42.01
    
  marketplacePricingSetting:
    type: object
    required:
    - ruleType
    properties:
      ruleType:
        $ref: '#/definitions/marketplacePricingRuleType'
      value:
        $ref: '#/definitions/marketplacePricingValue'

  marketplacePricingRuleOperationType:
    type: string
    enum:
    - plus
    - minus
    example: plus
  
  marketplacePricingRuleUnit:
    type: string
    enum:
    - percent
    - amount
    example: percent

  marketplacePricingRuleType:
    type: string
    default: Same
    enum:
    - PercentIncrease
    - PercentDecrease
    - AmountIncrease
    - AmountDecrease
    - Same
#    x-lov: MarketplacePricingRuleType

  marketplaceShippingChargeRuleType:
    type: string
    default: Same
    enum:
    - PercentIncrease
    - PercentDecrease
    - AmountIncrease
    - AmountDecrease
    - Same
    - Fixed
#    x-lov: MarketplaceShippingChargeRuleType

  marketplaceInfo:
    type: object
    required:
    - code
    - name
    - sellerBackOfficeUrl
    - sellerBackOfficeCredentialPageUrl
    - imageUrl
    - subscriptionStatus
    - credentialStatus
    - shippingSettingsStatus
    - source
    properties:
      code:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'
      name:
        type: string
        description: The name of the marketplace
        example: Cdiscount
      sellerBackOfficeUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
      sellerBackOfficeCredentialPageUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
      imageUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
      subscriptionStatus:
        $ref: '#/definitions/marketplaceSubscriptionStatus'
      
      credentialStatus:
        $ref: '#/definitions/marketplaceCredentialStatus'
      shippingSettingsStatus:
        $ref: '#/definitions/marketplaceShippingSettingsStatus'
      source:
        type: boolean
        description: If true, this marketplace is the source of offers
        default: false
        example: false
  

      
  marketplaceSubscriptionReporting:
    type: object
    required:
    - status
    - messages
    properties:
      status:
        $ref: '#/definitions/marketplaceSubscriptionStatus'
# [Style Validator (3435b500-6281-4333-8352-65cf18d10cb8) : All model properties must have examples]: Field 'example' required in 'properties'
      messages:
        type: array
        items:
          $ref: '#/definitions/marketplaceSubscriptionMessage'


  marketplaceSubscriptionMessage:
    type: object
    required:
    - senderType
    - utcDate
    - status
    properties:
      senderType:
        $ref: '#/definitions/marketplaceSubscriptionMessageSenderType'
      utcDate:
        type: string
        format: date-time
        example: '2009-06-15T13:45:30Z'
      status:
        $ref: '#/definitions/marketplaceSubscriptionStatus'
      message:
        type: string
        example: Wrong shoes!
#      propertiesConcerned:
#        type: array
#        description: The properties concerned by the refusal
#        items:
#          type: string
#        example:
#        - firstName

      
  marketplaceSubscriptionMessageSenderType:
    type: string
    enum:
    - merchant
    - marketplace
    example: marketplace
    
  marketplaceOfferPublicationStatus:
    description: The Offer Importation status
    type: string
    enum:
    - disabled
    - enabled
    example: enabled
    
  merchantEvents:
    type: array
    items:
      $ref: '#/definitions/merchantEvent'
      
  merchantEvent:
    type: object
    properties:
      eventType:
        type: string
      eventContent: 
        type: object