info:
  version: "1.0"
  title: IMN - Offer Exportation Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.Offer.EXP
  apiName: TBD
  namespace: IMN.Offer.EXP.Events
  comment: |
    IMN.Offer.EXP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Offer.Schemas
  - IMN.Offer.Events

definitions:


  offerExportInitializationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationCompleted:
    x-format: Event
    type: object
    required:
    - merchantCode
    - marketplaceCode
    - merchantOffers
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      marketplaceCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceCode'

  offerExportInitializationExpired:
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    
  offerExportInitializationDisabled:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    
  initializationExportStartRequested: 
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    
  offerInitializationStopped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'