info:
  version: "1.0"
  title: IMN - Offer Exportation Events

x-beezup-ops:
  codeGenType: domain
  product: IMN-CORE
  repo: IMN
  appRoot: IMN.Offer.EXP.Events
  apiName: IMN.Offer.EXP.Events
  namespace: IMN.Offer.EXP.Events
  comment: |
    IMN.Offer.EXP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Offer.Schemas
  - IMN.Offer.Events
  - System.Collections.Generic

definitions:

  offerExportInitializationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'



  offerExportInitializationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportPartitionStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionInitializationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - exportGlobalOperationType
      - partitionKey
      properties:
        operationType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportGlobalOperationType'
        partitionKey:
          type: string
        offerCount:
          type: integer
  
  offerExportPartitionPushStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionPushCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string  
  
  offerExportInitializationStopped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationExpired:
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      properties:
        totalOfferCount:
          type: integer      
        offerCountByPartition:
          type: object
          additionalProperties:
            type: integer
    
####################################

  offerExportUnpublicationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'



  offerExportUnpublicationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportPartitionUnpublicationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionUnpublicationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string
        offerCount:
          type: integer

  offerExportPartitionUnpublicationPushStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionUnpublicationPushCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string  
  
  
  offerExportUnpublicationStopped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportUnpublicationExpired:
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportUnpublicationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      properties:
        totalOfferCount:
          type: integer
        offerCountByPartition:
          type: object
          additionalProperties:
            type: integer