info:
  version: "1.0"
  title: IMN - Offer Exportation Events

x-beezup-ops:
  codeGenType: domain
  product: IMN-CORE
  repo: IMN
  appRoot: IMN.Offer.EXP.Events
  apiName: IMN.Offer.EXP.Events
  namespace: IMN.Offer.EXP.Events
  comment: |
    IMN.Offer.EXP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Offer.Schemas
  - IMN.Offer.Events
  - System.Collections.Generic

definitions:

  offerExportOperationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - operationType
      - parentOperationName
      properties: 
        operationType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationType'
        parentOperationName:
          type: string



  offerExportOperationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - operationType
      properties: 
        operationType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationType'



  offerExportPartitionOperationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionOperationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - exportGlobalOperationType
      - partitionKey
      properties:
        operationType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportGlobalOperationType'
        partitionKey:
          type: string
        offerCount:
          type: integer
  
  offerExportPartitionPushStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string

  offerExportPartitionPushCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - partitionKey
      properties:
        partitionKey:
          type: string  
  
  offerExportOperationStopped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportOperationExpired:
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportOperationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      properties:
        totalOfferCount:
          type: integer      
        offerCountByPartition:
          type: object
          additionalProperties:
            type: integer