info:
  version: "1.0"
  title: IMN - Offer Exportation Events

x-beezup-ops:
  codeGenType: domain
  product: IMN-CORE
  repo: IMN
  appRoot: IMN.Offer.EXP.Events
  apiName: IMN.Offer.EXP.Events
  namespace: IMN.Offer.EXP.Events
  comment: |
    IMN.Offer.EXP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Offer.Schemas
  - IMN.Offer.Events
  - System.Collections.Generic

definitions:

  offerExportOperationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - operation
      - parentOperationName
      properties: 
        operation:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationName'
        parentOperationName:
          type: string



  offerExportOperationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - operation
      properties: 
        operation:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationName'
      


  offerExportPartitionOperationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - operation
      - step
      - partitionKey
      properties: 
        operation:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationName'
        step:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationStepName'     
        partitionKey:
          type: string



  offerExportPartitionOperationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - operation
      - step
      - partitionKey
      properties: 
        operation:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationName'
        step:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationStepName'          
        partitionKey:
          type: string
        offerCount:
          type: integer
  
 

          
  offerExportOperationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - operation
      - processingStatus
      properties: 
        operation:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_export-schemas/1.0#/definitions/exportOperationName'
        processingStatus:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/processingStatus'
        errorMessage:
          type: string