info:
  version: "1.0"
  title: IMN - Offer Exportation Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.Offer.EXP
  apiName: TBD
  namespace: IMN.Offer.EXP.Events
  comment: |
    IMN.Offer.EXP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.Offer.Schemas
  - IMN.Offer.Events

definitions:

  offerExportInitializationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationStopped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationExpired:
    x-format: Event
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'

  offerExportInitializationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'