### Domains, a place to put your reusable components

### Examples...

info:
  version: '1.0'
  title: IMN - ADAPTER - Offer Importation Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  product: IMN-ADPT
  appRoot: IMN.ADPT.OfferIMP..Events
  apiName: IMN.ADPT.OfferIMP.Events
  namespace: IMN.ADPT.OfferIMP.Events
  comment: |
    IMN.ADPT.OfferIMP.Events
    changed to yaml format
  using:
  - IMN.Schemas
  - BeezUP2.ApiModels.Generated.Models.Generated
  #- UserErrorMessage=BeezUP2.ApiModels.Generated.Models.Generated.UserErrorMessage
  references:
  - IMN.Schemas


definitions:

  offerImportationStartRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'


  offerImportationStarted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - credential
      properties:
        credential:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceApiCredential'


  offerImportationExpired:
    x-format: Event
    description: Sent in the reminder to expire the process if it's expired
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - lastMessageIdApplied
      properties:
        lastMessageIdApplied:
          type: string
          format: MessageId
          description: The last message identifier applied on the aggregate



  offerImportationFetchPartitionCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - partitionKey
      properties:
        partitionKey:
          type: string
          description: The offer partition identifier




  offerImportationPreparationPartitionCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - partitionKey
      properties:
        partitionKey:
          type: string
          description: The offer partition identifier
          

  offerImportationPageFetched:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - pageNumber
      - offerCount
      properties:
        pageNumber:
         $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/pageNumber'
        offerCount:
          type: integer
          description: The offer count in the page
          example: 100




  offerImportationPreparationAllPartitionsCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - partitionKeys
      properties:
        partitionKeys:
          type: array
          description: The offer partition identifier list
          items:
            type: string
        offerCreatedCount:
          type: integer
          description: The offer created count
        offerUpdatedCount:
          type: integer
          description: The offer updated count
        offerUnchangedCount:
          type: integer
          description: The offer unchanged count
        offerDeletedCount:
          type: integer
          description: The offer deleted count




  offerImportationSendPartitionCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - partitionKey
      properties:
        partitionKey:
          type: string
          description: The offer partition identifier



  offerImportationFailed:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - merchantCode
      - marketplaceCode
      - operationNameInCause
      - errors
      properties:
        operationNameInCause:
          type: string
        errors:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userErrorMessage'
        

  offerImportationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - merchantCode
      - marketplaceCode
      - success
      properties:
        success:
          type: boolean
          
  offerImportationSubscriptionCreated:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - subscriptionId
      properties:
        subscriptionId:
          type: string
          description: The subscription id received from the marketplace


  offerImportationSubscriptionDeleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - subscriptionId
      properties:
        subscriptionId:
          type: string
          description: The subscription id deleted from the marketplace

  offerImportationReportGenerationRequested:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - reportId
      properties:
        reportId:
          type: string
          description: The report identifier received from the marketplace
        
  offerImportationReportGenerationChecked:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - reportId
      properties:
        reportId:
          type: string
          description: The report identifier received from the marketplace
        reportStatus:
          type: string
          description: The report status received from the marketplace

  offerImportationReportGenerationFailed:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required:
      - merchantCode
      - marketplaceCode
      - operationNameInCause
      - errors
      properties:
        operationNameInCause:
          type: string
        errors:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userErrorMessage'

  offerImportationReportGenerationCompleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    
    - type: object
      required:
      - success
      properties:
        success:
          type: boolean
        url:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'