info:
  description: IMN Core - Order Events
  version: '1.0'
  title: IMN - Order Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.Order.Events
  apiName: TBD
  namespace: IMN.Order.Events
  comment: |
    IMN.Order.Events
  using:
  - IMN.Schemas
  - IMN.Order.Schemas
  - BeezUP2.Framework.Processing
  references:
  - IMN.Order.Schemas

definitions:

  orderReceived:
    x-format: Event
    description: |
      This event his a technical one. It is stored in the event hub before it's processed by the OrderActor.
      The order actor will create business event like order created or updated.
      OrderReceived will be not be stored in the Event Store.
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderMarketplaceInfo'

  orderMerchantInfoConfigured:
    x-format: Event
    type: object
    required:
    - order
    - merchantInfo
    - userId
    - userEmail
    - userIPAddress
    properties:
      order:
        $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderIdentifier'
      merchantInfo:
        $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderMerchantInfo'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      userEmail:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
      userIPAddress:
        description: The IP address who request this operation
        type: string
        example: '127.0.0.1'

  orderMerchantInfoCleared:
    x-format: Event
    type: object
    required:
    - order
    - userId
    - userEmail
    - userIPAddress
    properties:
      order:
        $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderIdentifier'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      userEmail:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
      userIPAddress:
        description: The IP address who request this operation
        type: string
        example: '127.0.0.1'

  orderChangeEventBase:
    x-exclude: true
    allOf:
    #- $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/eventBase'
    - type: object
      discriminator: eventName
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - testMode
      - sourceType
      - eventType
      properties:
        order:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderIdentifier'
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        userName:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderChangeUserName'
        userEmail:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
        userIPAddress:
          description: The IP address who request this operation
          type: string
          example: '127.0.0.1'
        testMode:
          description: This operation was a test
          type: boolean
          example: false
        sourceType:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/operationSourceType'
        eventType:
          type: string
          description: The event type occured on the order

  orderAccepted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'

  orderRefused:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'

  orderShipped:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'
    - type: object
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - carrierCode
      - trackingNumber
      - testMode
      - sourceType
      properties:
        carrierCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/carrierCode'
        trackingNumber:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/trackingNumber'

  orderShippedWithTrackingUrl:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'
    - type: object
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - carrierName
      - trackingNumber
      - trackingUrl
      - testMode
      - sourceType

      properties:
        carrierName:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/carrierName'
        trackingNumber:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/trackingNumber'
        trackingUrl:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/trackingUrl'

  orderRefunded:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'
    - type: object
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - refundReason
      - testMode
      - sourceType
      properties:
        refundReason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/refundReason'

  orderCancelled:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'
    - type: object
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - cancellationReason
      - testMode
      - sourceType
      properties:
        cancellationReason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/cancellationReason'

  orderChangeCompleted:
    x-format: Event
    type: object
    required:
    - order
    - status
    properties:
      order:
        $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/orderIdentifier'
      status:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/processingStatus'
      error:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userErrorMessage'
        
        
  orderShipmentOverdue:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/order-events/1.0#/definitions/orderChangeEventBase'
    - type: object
      required:
      - order
      - userId
      - userName
      - userEmail
      - userIPAddress
      - cancellationReason
      - testMode
      - sourceType
      properties:
        cancellationReason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/order-schemas/1.0#/definitions/cancellationReason'