### Domains, a place to put your reusable components

### Examples...

info:
  version: '1.0'
  title: IMN - Merchant Commands
  description: IMN - Merchant Commands

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: TBD
  apiName: TBD
  namespace: IMN.MER.Commands
  comment: |
    IMN.MER
    changed to yaml format
  using:
  - IMN.Schemas
  - IMN.MER.Schemas

definitions:

  
  createMerchant:
    x-format: Command
    description: When the merchant creates his account on IMN
    type: object
    required: 
    - merchantCode
    - userId
    - companyName
    - email
    - lastName
    - firstName
    - country
    - phoneNumber
    - currencyCode
    - ecommerceSoftwareName
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      companyName:
        $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantCompanyName'
      email:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/email'
      lastName:
        type: string
      firstName:
        type: string
      country:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/countryIsoCodeAlpha3'
      phoneNumber:
        type: string
      imageUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
      currencyCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/currencyCode'
      ecommerceSoftwareName:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/ecommerceSoftwareName'
  
  updateMerchantAcountInfo:
    x-format: Command
    description: When the merchant updates his account information
    type: object
    required: 
    - merchantCode
    - userId
    - companyName
    - lastName
    - firstName
    - country
    - phoneNumber
    - currencyCode
    - ecommerceSoftwareName
    properties:
      merchantCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
      userId:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      companyName:
        $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantCompanyName'
      lastName:
        type: string
      firstName:
        type: string
      country:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/countryIsoCodeAlpha3'
      phoneNumber:
        type: string
      imageUrl:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'
      currencyCode:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/currencyCode'
      ecommerceSoftwareName:
        $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/ecommerceSoftwareName'

  declareMerchantOffersSourceMarketplace:
    x-format: Command
    description: When the merchant wants to declare this marketplace as offers's source 
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'



  undeclareMerchantOffersSourceMarketplace:
    x-format: Command
    description: When the merchant wants to undeclare this marketplace as offers's source 
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      
  acceptMerchantMarketplaceSubscription:
    x-format: Command
    description: When the marketplace configures credential and accepts the merchant subscription 
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
      
  refuseMerchantMarketplaceSubscription:
    x-format: Command
    description: When the marketplace refuses the merchant subscription 
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - reason
      properties:
        reason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantMarketplaceSubscriptionRefusalReason'
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
          
  blockMerchantMarketplaceSubscription:
    x-format: Command
    description: When the marketplace blocks the merchant subscription 
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - reason
      properties:
        reason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/merchantMarketplaceSubscriptionRefusalReason'
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'

      
  configureMerchantMarketplaceCredential:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - credential
      properties:
        credential:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceApiCredential'
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
  
  
  
  
  enableMerchantMarketplace:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
    
  disableMerchantMarketplace:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
  
  

  reenableMerchantMarketplaceOrderImportation:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
    
  disableMerchantMarketplaceOrderImportation:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      properties:
        userId:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
          
  configureMarketplacePricingSetting:
    x-format: Command
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - pricingSetting
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        pricingSetting:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplacePricingSetting'
          
  configureMarketplaceShippingSettings:
    x-format: Command
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - shippingSettings
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        shippingSettings:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/marketplaceShippingSettings'

  disableMarketplaceShippingDeliverySettings:
    x-format: Command
    description: Not for the MVP
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - userId
      - deliveryMode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        deliveryMode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/deliveryMode'

  reenableMarketplaceShippingDeliverySettings:
    x-format: Command
    description: Not for the MVP
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - userId
      - deliveryMode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        deliveryMode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-schemas/1.0#/definitions/deliveryMode'


          
  configureMarketplaceMerchantCode:
    x-format: Command
    allOf: 
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - userId
      - marketplaceCode
      - marketplaceMerchantCode
      properties:
        userId: 
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/userId'
        marketplaceMerchantCode:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceMerchantCode'