### Domains, a place to put your reusable components

### Examples...

info:
  description: IMN Core - Offer Events 
  version: '1.0'
  title: IMN - Offer Events

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  product: IMN-CORE
  appRoot: IMN.Offer.Events
  apiName: TBD
  namespace: IMN.Offer.Events
  comment: |
    IMN.Offer.Events
    changed to yaml format
  using:
  - IMN.Offer.Schemas
  - IMN.Schemas

definitions:


  
  
  merchantOfferEventBase:
    x-exclude: true
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOffer'

  merchantOfferReceived:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/offer-events/1.0#/definitions/merchantOfferEventBase'

  



  merchantOfferDeleted:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'
    
  merchantOfferUnpublished:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'
    - type: object
      required:
      - reason
      properties:
        reason:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferUnpublicationReasonCode'

  
  


  merchantOfferNotImported:
    x-format: Event
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferIdentifier'
    - type: object
      properties:
        reasons:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/IMN/offer-schemas/1.0#/definitions/merchantOfferNoneImportationReason'
          
#  MerchantOfferPushQueueReminded:
#    x-format: Event
#    x-exclude: true
#    description: The merchant offer pusher is reminded
#    allOf:
#    - type: object
#      required: 
#      - merchantCode
#      - senderMessageId
#      properties:
#        merchantCode:
#          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantCode'
#        senderMessageId:
#          type: string
#          format: MessageId
#          description: The sender message Id