### Domains, a place to put your reusable components

### Examples...

info:
  version: '1.0'
  title: IMN - ADAPTER - Offer Importation Domain

x-beezup-ops:
  codeGenType: domain
  repo: IMN
  appRoot: IMN.ADPT.OfferIMP.Commands
  apiName: IMN.ADPT.OfferIMP.Commands
  namespace: IMN.ADPT.OfferIMP.Commands
  comment: |
    IMN.ADPT.OfferIMP.Commands
    changed to yaml format
  using:
  - IMN.Schemas


definitions:




  prepareOfferImportation:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - credential
      properties:
        credential:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/marketplaceApiCredential'
        offerImportationTimeoutInMinutes:
          type: number
          format: double
          
  importExistingOffers:
    x-format: Command
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/merchantMarketplaceBase'
    - type: object
      required: 
      - merchantCode
      - marketplaceCode
      - sourceUri
      - timeoutInMinutes
      properties:
        timeoutInMinutes:
          type: number
          format: double
        sourceUri:
          $ref: 'https://api.swaggerhub.com/domains/IMN/imn.io/v1#/definitions/httpUrl'